# Generated by Django 3.0.6 on 2020-05-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schedule_workingtime'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='security_question',
        ),
        migrations.RemoveField(
            model_name='user',
            name='serurity_answer',
        ),
    ]
