# Generated by Django 3.0.6 on 2020-05-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200513_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='weekDay',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=31),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='workingTime',
            field=models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening')], default='morning', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('NA', 'N/A')], default='male', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff')], default='Staff', max_length=31),
        ),
    ]
