# Generated by Django 3.0.6 on 2020-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200513_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='weekDay',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='tuesday', max_length=31),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='workingTime',
            field=models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening')], default='afternoon', max_length=31),
        ),
    ]
