# Generated by Django 3.0.6 on 2020-05-13 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'AVAILABLE'), ('notAvailable', 'NOT AVAILABLE')], default='available', max_length=31)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
