# Generated by Django 3.0.6 on 2020-05-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_category_payment_product_productused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catetory',
            new_name='category',
        ),
    ]
