# Generated by Django 3.0.6 on 2020-05-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_payment_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='totalHourSpend',
        ),
    ]
