# Generated by Django 3.0.6 on 2020-05-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='workingTime',
            field=models.CharField(choices=[('MORNING', 'morning'), ('AFTERNOON', 'afternoon'), ('EVENING', 'evening')], default='MORNING', max_length=10),
        ),
    ]
