# Generated by Django 3.0.6 on 2020-06-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200626_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklySchechule',
            new_name='WeeklySchedule',
        ),
    ]
